import { IUpdateBankInfoPayloadRtn } from './types'

export const initialState: IUpdateBankInfoPayloadRtn = {
  success: false,
  data: [
    {
      id: '',
      user_id: '',
      parent_branch_id: '',
      store_logo: '',
      store_name: '',
      whatsapp_num: '',
      whatsapp_username: '',
      whatsapp_password: '',
      business_url: '',
      industry_id: '',
      industry_types: '',
      description: '',
      images: '',
      email: '',
      website: '',
      ntn_num: '',
      street_address: '',
      latitude: '',
      longitude: '',
      country: '',
      is_online: 0,
      phone_number: '',
      mobile_number: '',
      city: '',
      state: '',
      postal_code: '',
      area: '',
      bank_phone: '',
      payment_method: '',
      created_at: '',
      updated_at: '',
      deleted_at: '',
      acc_holder_mobile_number: '',
      acc_holder_name: '',
      paypal_email: '',
      bank_name: '',
      acc_number: '',
      iban_number: '',
      passport_number: '',
      swift_code: '',
      service_charges_amount: '',
      currency: '',
      shipping_percentage_type: '',
      shipping_percentage: '',
      applicable_range: '',
      delivery_hours: '',
      delivery_minutes: '',
      delivery_range: '',
      delivery_radius: '',
      store_timings: '',
      discount_amount: '',
      service_options: '',
      free_trial_start_date: new Date(),
      qrcode_img: '',
      subscription_canceled_status: 0,
      subscription_canceled_date: new Date(),
      subscription_restart_date: new Date(),
      status: 0,
      cash_on_delivery: '',
      service_charges_status: '',
      cod_status: '',
      auto_subscription: '',
      orders_accept_status: '',
      is_tax_enable: 0,
      tax_rate: '',
      is_tax_included: 0,
      custom_tax_config: '',
      allow_checkout_when_out_of_stock: '',
      min_order_price: '',
      max_order_price: '',
      min_order_qty: '',
      max_order_qty: '',
      disount_type: '',
      delivery_timming: '',
      product_sorting: '',
      timezone: '',
      is_approved: 0
    }
  ],
  message: ''
}
